version: '3.7'

services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    networks:
      - wordpress-network
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
    deploy:
      mode: global

  db:
    image: mysql
    networks:
      - wordpress-network
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspass
      MYSQL_ROOT_PASSWORD: root-secret-Password
    deploy:
      mode: global

networks:
  wordpress-network:
